### ISSUE TITLE
Trying to use the lib!

### ISSUE THREAD

**Issue by altieres** [gmtii/ili9341-arduino#1]
Hi @gmtii, I'm trying to use the lib, but it isn't working with my Arduino Uno and http://dx.com/p/2-2-serial-spi-tft-color-lcd-module-for-arduino-red-silver-234675.

Just the backlight is on, the screen is just white... Can you help me some way?

**Comment by gmtii** [comment]
hi,

can you post your serial log and connections?

**Comment by altieres** [comment]
Yes! I'll do it tonight.

Thank you!

**Comment by altieres** [comment]
@gmtii, I was connecting arduino output (5V) directly to the LCD inputs (2.5V - 3.3V).
With two 1K resistors dividing voltage, for each input, it worked!
Thank you for willing to help me.
